### ISSUE TITLE
iOS 9 Collection view cell width wrong at appearance

### ISSUE THREAD

**Issue by clemenation** [jessesquires/JSQMessagesViewController#1257]
I ran into this problem after updating to Xcode 7 & iOS9 SDK:
Immediately after the VC is pushed, the collection view cell width is smaller than the screen width. A reloadData on the collectionView is needed in order to restore the cell width to match screen width. It's not happening all the time but occasionally with chat dialogs that have a lot of messages/data to display.
![screen shot 2015-10-13 at 1 03 07 pm](https://cloud.githubusercontent.com/assets/545146/10443940/229e2e7a-71ac-11e5-9cc6-3a6a629caf22.png)

**Comment by zigdanis** [comment]
I'm having similar issue like this. Only on iOS 9 and if it's iPhone 6. on iPhone 5 everything is all right.
Here is my screenshot.
![screen shot 2015-10-14 at 18 28 54](https://cloud.githubusercontent.com/assets/1284116/10488514/af857834-72a1-11e5-9778-869ce55fc6bd.png)

**Comment by fanly** [comment]
how to replace it?

**Comment by jardamach** [comment]
@fanly @zigdanis: This is happening because the loaded xib file (with chat collection view) has wrong frame (in this case frame.size.width) in **viewDidLoad** or **viewWillAppear** because it's not properly laid out yet. You can get proper collectionView size in **viewDidLayoutSubviews** method.

Now, the problem is connected to **JSQMessagesBubblesSizeCalculator** - cell sizes are calculated right after **viewWillAppear**. When calculating cell size they are using this wrong width value and the result is stored in cache and reused afterwards. 

A quick fix is to place: 
```
- (void)viewDidLayoutSubviews {
    
    [super viewDidLayoutSubviews];
    
    // invalidate layout
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
}
```

cc: @jessesquires

**Comment by fanly** [comment]
@jessesquires 
how to use "previousCollectionViewFrameWidth"?

**Comment by jardamach** [comment]
@fanly It is just a custom CGFloat value which is set in viewDidLoad like this:

 ```
self.previousCollectionViewFrameWidth = CGRectGetWidth(self.collectionView.frame);
```

**Comment by erichedstrom** [comment]
@jardamach Thanks! This saved me a lot of time.

Adding this -viewDidLayoutSubviews did the trick for me, with one additional change: I had to set invalidateFlowMessagesCache to YES on the invalidation context. You mentioned this in your comment, but your sample code didn't have it.

    // invalidate layout
    JSQMessagesCollectionViewFlowLayoutInvalidationContext *context = [JSQMessagesCollectionViewFlowLayoutInvalidationContext context];
    context.invalidateFlowLayoutMessagesCache = YES;
    [self.collectionView.collectionViewLayout invalidateLayoutWithContext:context];

**Comment by jessesquires** [comment]
Hello all -- I believe this is a dupe of #1212 and was fixed by #1238.

Can anyone confirm?

**Comment by jardamach** [comment]
@jessesquires I believe that #1238 is not a fix of this issue (But can't really say 100% now - I did just a really quick test on my version). The thing is that this is not a rotation related issue - happens right after chat presentation. In #1238 there are two methods invalidating bubble size cache:

**traitCollectionDidChange** - called after viewWillAppear but chat.view.frame is not yet correct and recalculating bubble sizes gives incorrect values.
**viewWillTransitionToSize** - not called after viewWillAppear

Maybe @harlanhaskins could comment on this one as well.

**Comment by clemenation** [comment]
@jardamach Your solution's still not working in my case though. Any thought?

**Comment by yoxisem544** [comment]
Hi, does any figure out anything? I've tried all the quick fix, but non of them worked.

**Comment by jessesquires** [comment]
hey all -- I can repro this with the demo project on an iPhone 6 device.

can anyone provide further steps?

**Comment by erichedstrom** [comment]
@jessesquires Thanks for following up! I can verify that #1238 fixes it for the demo project, but not for my app.

For some reason in the demo app the width of the view has already changed from 320 (width in the .XIB) to 375 (iPhone 6 width) when -traitCollectionDidChange: is called, and so the call to jsq_resetLayoutAndCaches invalidates and recalculates the layout before the view has appeared.

But in my app (and others, it looks like), the view is still 320 wide when traitCollectionDidChange: is called, and so the layout needs to be invalidated again when viewDidLayoutSubviews: is called. I suppose it's because it's loading the chat entries from Core Data.

I'll submit a pull request based on @jardamach 's fix.

**Comment by jessesquires** [comment]
Hm... @erichedstrom can you provide more details about your setup? Xcode version, iOS versions, devices, etc.

**Comment by erichedstrom** [comment]
@jessesquires Xcode 7.3.1, iPhone 6 with 9.3.2, and iPhone 6 Simulator 9.3. Base deployment target for app is iOS 8.1.

Aha! The demo app shows the problem as well if I change the deployment target from iOS 7 to 8.1.

**Comment by erichedstrom** [comment]
Specific steps:
Set deployment target to iOS 8.1.
Run the demo app on an iPhone 6/6s or 6/6s simulator.
Tap Push via Storyboard or Push programmatically.
View will appear with bubbles sized appropriately for an iPhone 5.
Start to pull down Notification Center.
Bubbles will suddenly resize to fit the iPhone 6.

**Comment by jessesquires** [comment]
Thanks @erichedstrom !

So I followed those steps but still couldn't repro. Did you pull the latest from `master` ?

**Comment by erichedstrom** [comment]
Ach, yes, I did have the latest from master, but now I can't repro with the demo app either.

The bottom line is the fix in #1238 expects the view from the xib to have been resized before traitCollectionDidChange: is called, while the view is not guaranteed to have been resized until viewDidLayoutSubviews is called. (I don't see viewWillTransitionToSize:withTransitionCoordinator: being called at all.)

**Comment by jessesquires** [comment]
Hm... weird. 

`viewWillTransitionToSize:withTransitionCoordinator:` would only be called on rotations.

Have you tried invalidating on `viewWillAppear:` ?

**Comment by erichedstrom** [comment]
Thanks for following up. 

I did try invalidating in viewWillAppear, and the base class also invalidates in a block called from its viewWillAppear.

I also have in viewWillAppear a [self scrollToBottomAnimated:YES] after calling [super viewWillAppear]. If I comment out my call to scrollToBottomAnimated:, the cells are sized correctly right off the bat, but you can see it scrolling to the bottom a second time as the view is sliding in from the right. So I'm going to stick with @jardamach 's fix above.

If I am ever able to track down and reproduce the problem consistently in the demo app I will let you know. It seems like you might as well close this again because no one else is speaking up about it.

**Comment by sobakasu** [comment]
not sure if it's the same issue, but I have layout issues with the message cells in iOS 9 on ipad after rotation. I have found turning on 'Requires full screen' fixes the issue (but prevents the app using Slide Over and Split View)

**Comment by fans3210** [comment]
I'm having the same problem on iphone 6s simulator. Iphone 5s is fine.
The issue on iphone 6 simulator is: 
If I load message from internet or from cache, the bubble size is ok.
Once I store that message in a local variable and go go back to the chat page again using navigation controller and load that chat massage from memory, the bubble width become about 30px smaller.

I tracked down the calculation process and found the issue is in the JSQMessagesBubblesSizeCalculator ,  in 

- (CGSize)messageBubbleSizeForMessageData:(id<JSQMessageData>)messageData
                              atIndexPath:(NSIndexPath *)indexPath
                               withLayout:(JSQMessagesCollectionViewFlowLayout *)layout

The "stringRect" gave me different results for message load from cache and from memory. There is a 30px difference although their [messageData text] are the same.  I used subclass of jsqmessage.

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Comment by GalKeidar10** [comment]
Right, the problem is when you load from nib.

I fixed it with this:

`@implementation ChatVC

- (void)viewDidLoad {
    [super viewDidLoad];
    
    CGRect frame = self.collectionView.frame;
    frame.size.width = CGRectGetWidth(self.view.frame);
    self.collectionView.frame = frame;
}
`
