### ISSUE TITLE
Message bubble width truncated in master view controller of split view controller

### ISSUE THREAD

**Issue by JubrilO** [jessesquires/JSQMessagesViewController#1483]
#### General information

- Library version(s): 7.2.0
- iOS version(s): 9.1
- Devices/Simulators affected: iPad Air
- Reproducible in the demo project (Y/N): Not sure 
- Link to a project that exhibits the issue (if possible):
- List any related issues:

#### Expected behavior
> Bubble width should increase with increasing text and should span the width of the container view 

#### Actual behavior

> Bubble width does not increase with increasing text. Width does not exceed three characters 

#### Steps to reproduce the behavior

>  Just make your chatviewcontroller the mastervc of a splitvc

#### Screenshots or videos?

> 
![simulator screen shot 5 mar 2016 5 01 12 pm](https://cloud.githubusercontent.com/assets/4950888/13548689/30e96114-e2f6-11e5-9834-d593bc8e3ec7.png)

**Comment by jessesquires** [comment]
I think this was fixed by #1238.

Can you confirm?

**Comment by JubrilO** [comment]
I think the fix you're talking about was merged to the develop branch. I've tried using the develop branch, I still get the same results.

**Comment by jessesquires** [comment]
Try adjusting `messageBubbleLeftRightMargin`

http://cocoadocs.org/docsets/JSQMessagesViewController/7.2.0/Classes/JSQMessagesCollectionViewFlowLayout.html#//api/name/messageBubbleLeftRightMargin

**Comment by JubrilO** [comment]
It works!! Thanks a lot!  +1:
