### ISSUE TITLE
CollectionView won't scroll up when using 3rd-party keyboard app as input source

### ISSUE THREAD

**Issue by ShawnFoo** [jessesquires/JSQMessagesViewController#1625]
```
I have read all of the README, documentation, and FAQ.
I have reviewed the contributing guidelines. Confirmation: YES
I have searched existing issues and this is not a duplicate.
I also read original source codes relevent to this issue.(JSQKeyboardController, JSQViewController..etc)
```

---

Hi
   I found JSQCollectionView' content won't scroll up when 3rd keyboard(System keyboard is ok) pop up as input source for JSQTextView. Although the collectionView.offsetInsets are correct logging by breakpoint. 
   Any ideas that what I have missed  : [

**Comment by jessesquires** [comment]
Thanks @ShawnFoo ! 😄 

I'm pretty sure this is now fixed on `develop` if you want to try it out.

**Comment by SergioChan** [comment]
@jessesquires I tried the latest `develop` branch and this bug is still there... When I switch keyboard type from a lower height one to a higher one, the collectionView won't scroll up .. I just fixed it in my local project.. this is the screenshot from the latest `develop` branch..
![22](https://cloud.githubusercontent.com/assets/10103766/17474102/d953c14a-5d86-11e6-8ee6-5bd9adc30c99.jpg)

**Comment by jessesquires** [comment]
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq
