### ISSUE TITLE
Unknown Class in SWIFT

### ISSUE THREAD

**Issue by Edig** [jessesquires/JSQMessagesViewController#790]
Hi I'm trying to implement JSQ with swift, but I'm getting this errors. I don't know why. any ideas?

    Unknown class JSQMessagesCollectionView in Interface Builder file.
    2015-02-13 15:52:38.932 [9805:3062176] Unknown class JSQMessagesCollectionViewFlowLayout in Interface Builder file.
     2015-02-13 15:52:38.933 [9805:3062176] Unknown class JSQMessagesComposerTextView in Interface Builder file.
     2015-02-13 15:52:38.948 [9805:3062176] -[JSQMessagesInputToolbar jsq_pinAllEdgesOfSubview:]: unrecognized selector sent to instance 0x7faebef46b70

    class MessagesScreenViewController: JSQMessagesViewController, UIActionSheetDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        self.title  = "Friend Message"
    }

**Comment by attheodo** [comment]
I had the same problem. The solution was go to `JSQMessagesViewController.m` and change the `bundle:` to `[NSBundle bundleForClass:[self class]]`

**Comment by Edig** [comment]
Hi @attheodo,

Thats already in the code

```
+ (UINib *)nib
{
    return [UINib nibWithNibName:NSStringFromClass([JSQMessagesViewController class])
                          bundle:[NSBundle bundleForClass:[self class]]];
}

+ (instancetype)messagesViewController
{
    return [[[self class] alloc] initWithNibName:NSStringFromClass([JSQMessagesViewController class])
                                          bundle:[NSBundle bundleForClass:[self class]]];
}
```

**Comment by jessesquires** [comment]
Hey @Edig - this has been fixed already (#773) but it is not yet in Cocoapods ([v6.1.4](https://github.com/jessesquires/JSQMessagesViewController/milestones)).

**Comment by attheodo** [comment]
Uhm sorry, [NSBundle bundleForClass:[JSQMessagesViewController class]]

**Comment by Edig** [comment]
@jessesquires, @attheodo. Thanks both but that didn't fix the problem. I already debug it and I know the problem is in those lines. But that didn't fix the problem.

The problem is in here

```
UINib *nib = [[self class] nib];
[nib instantiateWithOwner:self options:nil];
```

**Comment by jessesquires** [comment]
Thanks @Edig - are you using cocoapods, or not?

**Comment by Edig** [comment]
@jessesquires, yes I'm using cocoapods (I just install it with this plugin)

**Comment by Edig** [comment]
@jessesquires, I was checking other parts of the code, and I don't know why but  I think that the error its something with the pointers. The exact part where it crashes is

in ```JSQMessagesInputToolbar```
```[self jsq_pinAllEdgesOfSubview:toolbarContentView];```

It says unrecognised selector sent to class

I comment that and then I get this error

```[UIImage jsq_defaultAccessoryImage]: unrecognized selector sent to class```

**Comment by SantiMoskito** [comment]
Hi @Edig , did you solve the problem?? Please tell me how, I am stuck on this all of a sudden. @jessesquires  
The funny thing is that it worked some time ago, I dont now what and when did I do to break it.

My problem seems to be here , too (last call before Exception):
	3   UIKit                               0x000000010927b01a -[UINib instantiateWithOwner:options:] + 507
